### PR TITLE
Update for b3407 and b3411

### PR DESCRIPTION
**Pull request by Mr-X-GTA**
Fixes https://github.com/Mr-X-GTA/YimMenu/issues/54

Depends on https://github.com/Mr-X-GTA/GTAV-Classes-1/pull/2

### CODE REVIEW

**Comment by Deadlineem** [comment]
Nice work.  Would really love to know how to do this on my own, idk where to start with IDA and sigmaker though.

Works the same as previous update?  FSL= online with public and no FSL means solo/invite only?

**Comment by Skorchekd** [comment]
this wont work online. FSL needs to be updated. i wish remove the reliance on FSL...

**Comment by Skorchekd** [comment]
FSL isnt really open source either so we cant really do much about it...

**Comment by Deadlineem** [comment]
> this wont work online. FSL needs to be updated. i wish remove the reliance on FSL...

You don't need to rely on FSL, FSL is for two things currently.  1. Being able to get you online with other players (you can still go in solo or invite only sessions without FSL with the menu) and 2.  Keeping your account safe while letting you have control over your funds/assets in the game with no risk.

Using the mod online without FSL can be done though, just cant join players or let them join you

**Comment by lzq960605** [comment]
Why hasn't it been merged yet?

**Comment by Deadlineem** [comment]
> Why hasn't it been merged yet?

Because there may still be things he hasnt fixed with this update.  If you are in a rush, just clone the repo, open it with visual studio, add the changes he made to the correct files and compile it.

**Comment by YimMenuTheBest** [comment]
at this point when entering a solo session the game crashes.

Has anyone else tried this pull request?

**Comment by Deadlineem** [comment]
> at this point when entering a solo session the game crashes.
> 
> Has anyone else tried this pull request?

I will be trying it later on tonight, it says it depends on the update to gtav-classes and globals also need to be updated, so be sure to update those as well if youre doing this yourself.

**Comment by YimMenuTheBest** [comment]
> > at this point when entering a solo session the game crashes.
> > Has anyone else tried this pull request?
> 
> I will be trying it later on tonight, it says it depends on the update to gtav-classes and globals also need to be updated, so be sure to update those as well if youre doing this yourself.

my bad, the global ones, if you search for a solo session, send you to a public one, that's why sometimes it crashes and sometimes not.

I am just updating the Decompiled Scripts, but I have a curious problem with 3 files of the 1100 files, these last 3 are not decompiled and give error in the program, if someone can get them would be of great help to update the global.

freemode.ysc
fm_content_bussines_battles.ysc
fm_content_sightseeing.ysc

**Comment by L7NEG** [comment]
i will update the rest of globals

**Comment by L7NEG** [comment]
> i will update the rest of globals

after i checked the src globals i found out that MrxGTA already done it so great work fr

**Comment by L7NEG** [comment]
> > > at this point when entering a solo session the game crashes.
> > > Has anyone else tried this pull request?
> > 
> > 
> > I will be trying it later on tonight, it says it depends on the update to gtav-classes and globals also need to be updated, so be sure to update those as well if youre doing this yourself.
> 
> my bad, the global ones, if you search for a solo session, send you to a public one, that's why sometimes it crashes and sometimes not.
> 
> I am just updating the Decompiled Scripts, but I have a curious problem with 3 files of the 1100 files, these last 3 are not decompiled and give error in the program, if someone can get them would be of great help to update the global.
> 
> freemode.ysc fm_content_bussines_battles.ysc fm_content_sightseeing.ysc

you can use this fixed one https://github.com/maybegreat48/GTA-V-Script-Decompiler

**Comment by CSY0N** [comment]
crossmap needed be updated too

**Comment by YimMenuTheBest** [comment]
It seems that the hook/script_patch to allow or evading the restrictions to modify all vehicles in LSC has changed, now it does not allow to do it, can it be updated?

**Comment by lzq960605** [comment]
Updated more than 80 mb, version number 3411

**Pull request merged**
