### PR TITLE
Update for b3351

### PR DESCRIPTION
**Pull request by Mr-X-GTA**
Note that you must use FSL and be the session host

### CODE REVIEW

**Comment by Tessio** [comment]
Tested and working well, “as it should”. 

Thanks for the update

**Comment by bilalbasem** [comment]
should we expect an update that will fix the public session crash problem ? :)

**Comment by L7NEG** [comment]
> should we expect an update that will fix the public session crash problem ? :)

yes we just have to wait bro

**Comment by samanvx** [comment]
> > should we expect an update that will fix the public session crash problem ? :)
> 
> yes we just have to wait bro

I'm confused, what do we have to do to use YIM-Menu again?

**Comment by creenl1** [comment]
I looked for a bypass but couldn't find one, it looks like Rockstar did the right thing

**Pull request merged**
